services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    networks:
      - profeco
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  

  # Frontend 
  # TODO
  

  # Backend services
  
  api-cliente-web:
    image: silverflin/profeco-api-cliente-web:latest

  api-cliente-movil:
    image: silverflin/profeco-api-cliente-movil:latest

  api-tienda:
    image: silverflin/profeco-api-tienda:latest

  # --- Microservices --- 

  # Products microservice
  product-mongodb:
    image: mongo
    networks:
        - products_internal_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  products-microservice:
    image: silverflin/product-catalog-microservice:latest
    networks:
      - products_internal_network
      - profeco
    depends_on:
      rabbitmq:
        condition: service_healthy
      product-mongodb:
        condition: service_healthy

  # Reviews microservice
  reviews-mongodb:
    image: mongo
    networks:
        - reviews_internal_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  reviews-microservice:
    image: silverflin/reviews-microservice:latest
    networks:
      - reviews_internal_network
      - profeco
    depends_on:
      reviews-mongodb:
        condition: service_healthy

  # Customer Preferences microservice
  customer-preferences-mongodb:
    image: mongo
    networks:
        - preferences_internal_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  customer-preferences-microservice:
    image: silverflin/customer-preferences-microservice:latest
    networks:
      - preferences_internal_network
      - profeco
    depends_on:
      customer-preferences-mongodb:
        condition: service_healthy

networks:
  products_internal_network:
    driver: bridge
  profeco:
    driver: bridge
  reviews_internal_network:
    driver: bridge
  preferences_internal_network:
    driver: bridge
