services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    networks:
      - profeco
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  reports:
    image: mongo
    networks:
      - reports_internal_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  reports-microservice:

    image: silverflin/reports-microservice:latest
    networks:
      - reports_internal_network
      - profeco
    depends_on:
      reports:
        condition: service_healthy

networks:
  reports_internal_network:
    driver: bridge
  profeco:
    driver: bridge
