// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/preferences.proto

package preferences_microservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomerPreferencesClient is the client API for CustomerPreferences service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerPreferencesClient interface {
	AddVisitedProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*VisitedProductsList, error)
	GetVisitedProductList(ctx context.Context, in *PreferencesDefaultRequest, opts ...grpc.CallOption) (*VisitedProductsList, error)
	AddFavoriteMarket(ctx context.Context, in *FavoriteMarketRequest, opts ...grpc.CallOption) (*FavoriteMarketsList, error)
	GetFavoriteMarketsList(ctx context.Context, in *PreferencesDefaultRequest, opts ...grpc.CallOption) (*FavoriteMarketsList, error)
	AddProductToShoppingCart(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*ShoppingCart, error)
}

type customerPreferencesClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerPreferencesClient(cc grpc.ClientConnInterface) CustomerPreferencesClient {
	return &customerPreferencesClient{cc}
}

func (c *customerPreferencesClient) AddVisitedProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*VisitedProductsList, error) {
	out := new(VisitedProductsList)
	err := c.cc.Invoke(ctx, "/proto.CustomerPreferences/AddVisitedProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerPreferencesClient) GetVisitedProductList(ctx context.Context, in *PreferencesDefaultRequest, opts ...grpc.CallOption) (*VisitedProductsList, error) {
	out := new(VisitedProductsList)
	err := c.cc.Invoke(ctx, "/proto.CustomerPreferences/GetVisitedProductList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerPreferencesClient) AddFavoriteMarket(ctx context.Context, in *FavoriteMarketRequest, opts ...grpc.CallOption) (*FavoriteMarketsList, error) {
	out := new(FavoriteMarketsList)
	err := c.cc.Invoke(ctx, "/proto.CustomerPreferences/AddFavoriteMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerPreferencesClient) GetFavoriteMarketsList(ctx context.Context, in *PreferencesDefaultRequest, opts ...grpc.CallOption) (*FavoriteMarketsList, error) {
	out := new(FavoriteMarketsList)
	err := c.cc.Invoke(ctx, "/proto.CustomerPreferences/GetFavoriteMarketsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerPreferencesClient) AddProductToShoppingCart(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*ShoppingCart, error) {
	out := new(ShoppingCart)
	err := c.cc.Invoke(ctx, "/proto.CustomerPreferences/AddProductToShoppingCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerPreferencesServer is the server API for CustomerPreferences service.
// All implementations must embed UnimplementedCustomerPreferencesServer
// for forward compatibility
type CustomerPreferencesServer interface {
	AddVisitedProduct(context.Context, *AddProductRequest) (*VisitedProductsList, error)
	GetVisitedProductList(context.Context, *PreferencesDefaultRequest) (*VisitedProductsList, error)
	AddFavoriteMarket(context.Context, *FavoriteMarketRequest) (*FavoriteMarketsList, error)
	GetFavoriteMarketsList(context.Context, *PreferencesDefaultRequest) (*FavoriteMarketsList, error)
	AddProductToShoppingCart(context.Context, *AddProductRequest) (*ShoppingCart, error)
	mustEmbedUnimplementedCustomerPreferencesServer()
}

// UnimplementedCustomerPreferencesServer must be embedded to have forward compatible implementations.
type UnimplementedCustomerPreferencesServer struct {
}

func (UnimplementedCustomerPreferencesServer) AddVisitedProduct(context.Context, *AddProductRequest) (*VisitedProductsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVisitedProduct not implemented")
}
func (UnimplementedCustomerPreferencesServer) GetVisitedProductList(context.Context, *PreferencesDefaultRequest) (*VisitedProductsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitedProductList not implemented")
}
func (UnimplementedCustomerPreferencesServer) AddFavoriteMarket(context.Context, *FavoriteMarketRequest) (*FavoriteMarketsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFavoriteMarket not implemented")
}
func (UnimplementedCustomerPreferencesServer) GetFavoriteMarketsList(context.Context, *PreferencesDefaultRequest) (*FavoriteMarketsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFavoriteMarketsList not implemented")
}
func (UnimplementedCustomerPreferencesServer) AddProductToShoppingCart(context.Context, *AddProductRequest) (*ShoppingCart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProductToShoppingCart not implemented")
}
func (UnimplementedCustomerPreferencesServer) mustEmbedUnimplementedCustomerPreferencesServer() {}

// UnsafeCustomerPreferencesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerPreferencesServer will
// result in compilation errors.
type UnsafeCustomerPreferencesServer interface {
	mustEmbedUnimplementedCustomerPreferencesServer()
}

func RegisterCustomerPreferencesServer(s grpc.ServiceRegistrar, srv CustomerPreferencesServer) {
	s.RegisterService(&CustomerPreferences_ServiceDesc, srv)
}

func _CustomerPreferences_AddVisitedProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPreferencesServer).AddVisitedProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CustomerPreferences/AddVisitedProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPreferencesServer).AddVisitedProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerPreferences_GetVisitedProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreferencesDefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPreferencesServer).GetVisitedProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CustomerPreferences/GetVisitedProductList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPreferencesServer).GetVisitedProductList(ctx, req.(*PreferencesDefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerPreferences_AddFavoriteMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPreferencesServer).AddFavoriteMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CustomerPreferences/AddFavoriteMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPreferencesServer).AddFavoriteMarket(ctx, req.(*FavoriteMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerPreferences_GetFavoriteMarketsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreferencesDefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPreferencesServer).GetFavoriteMarketsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CustomerPreferences/GetFavoriteMarketsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPreferencesServer).GetFavoriteMarketsList(ctx, req.(*PreferencesDefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerPreferences_AddProductToShoppingCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPreferencesServer).AddProductToShoppingCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CustomerPreferences/AddProductToShoppingCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPreferencesServer).AddProductToShoppingCart(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerPreferences_ServiceDesc is the grpc.ServiceDesc for CustomerPreferences service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerPreferences_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CustomerPreferences",
	HandlerType: (*CustomerPreferencesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddVisitedProduct",
			Handler:    _CustomerPreferences_AddVisitedProduct_Handler,
		},
		{
			MethodName: "GetVisitedProductList",
			Handler:    _CustomerPreferences_GetVisitedProductList_Handler,
		},
		{
			MethodName: "AddFavoriteMarket",
			Handler:    _CustomerPreferences_AddFavoriteMarket_Handler,
		},
		{
			MethodName: "GetFavoriteMarketsList",
			Handler:    _CustomerPreferences_GetFavoriteMarketsList_Handler,
		},
		{
			MethodName: "AddProductToShoppingCart",
			Handler:    _CustomerPreferences_AddProductToShoppingCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/preferences.proto",
}
