
services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    networks:
      - profeco
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  product-mongodb:
    image: mongo
    networks:
        - products_internal_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet


  products-microservice:
    image: silverflin/product-catalog-microservice:latest
    networks:
      - products_internal_network
      - profeco
    depends_on:
      rabbitmq:
        condition: service_healthy
      product-mongodb:
        condition: service_healthy

networks:
  products_internal_network:
    driver: bridge
  profeco:
    driver: bridge
