
services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - profeco
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  mongodb:
    image: mongo
    container_name: product-mongodb
    ports:
      - "127.0.0.1:27017:27017"
    networks:
        - products_internal_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet


  products-microservice:
    # build:
    # context: .
    # dockerfile: Dockerfile
    image: silverflin/product-catalog-microservice:latest
    ports:
      - "0.0.0.0:50051:50051"
    networks:
      - products_internal_network
      - profeco
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

networks:
  products_internal_network:
    driver: bridge
  profeco:
    driver: bridge
