
services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    networks:
      - profeco
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  deals-mongodb:
    image: mongo
    networks:
      - deals_internal_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet


  deals-microservice:
    image: silverflin/deals-microservice:latest
    networks:
      - deals_internal_network
      - profeco
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

networks:
  deals_internal_network:
    driver: bridge
  profeco:
    driver: bridge
